        // Monaco's SQL language adds highlighting, but does not provide a complete
        // T-SQL completion catalog. Keep the static language items here so they are
        // available even before database metadata has finished loading.
        var tsqlKeywords = [
            "ADD", "ALL", "ALTER", "AND", "ANY", "APPLY", "AS", "ASC", "AUTHORIZATION",
            "BACKUP", "BEGIN", "BETWEEN", "BREAK", "BROWSE", "BULK", "BY", "CASCADE",
            "CASE", "CHECK", "CHECKPOINT", "CLOSE", "CLUSTERED", "COLLATE", "COLUMN",
            "COMMIT", "COMPUTE", "CONSTRAINT", "CONTAINS", "CONTAINSTABLE", "CONTINUE",
            "CREATE", "CROSS", "CURRENT", "CURRENT_DATE", "CURRENT_TIMESTAMP", "CURSOR",
            "DATABASE", "DBCC", "DEALLOCATE", "DECLARE", "DEFAULT", "DELETE", "DENY",
            "DESC", "DISABLE", "DISTINCT", "DISTRIBUTED", "DOUBLE", "DROP", "DUMP",
            "ELSE", "ENABLE", "END", "ERRLVL", "ESCAPE", "EXCEPT", "EXEC", "EXECUTE",
            "EXISTS", "EXIT", "EXTERNAL", "FETCH", "FILE", "FILLFACTOR", "FOR", "FOREIGN",
            "FREETEXT", "FREETEXTTABLE", "FROM", "FULL", "FUNCTION", "GO", "GOTO", "GRANT",
            "GROUP", "HAVING", "HOLDLOCK", "IDENTITY", "IDENTITY_INSERT", "IDENTITYCOL", "IF",
            "IN", "INCLUDE", "INDEX", "INNER", "INSERT", "INTERSECT", "INTO", "IS", "JOIN",
            "KEY", "KILL", "LEFT", "LIKE", "LINENO", "LOAD", "MERGE", "NATIONAL", "NOCHECK",
            "NONCLUSTERED", "NOT", "NULL", "NULLS", "OF", "OFF", "OFFSETS", "ON", "OPEN",
            "OPENDATASOURCE", "OPENQUERY", "OPENROWSET", "OPENXML", "OPTION", "OR", "ORDER",
            "OUTER", "OVER", "PERCENT", "PIVOT", "PLAN", "PRECISION", "PRIMARY", "PRINT",
            "PROC", "PROCEDURE", "PUBLIC", "RAISERROR", "READ", "READTEXT", "RECONFIGURE",
            "REFERENCES", "REPLICATION", "RESTORE", "RESTRICT", "RETURN", "REVERT", "REVOKE",
            "RIGHT", "ROLLBACK", "ROWGUIDCOL", "RULE", "SAVE", "SCHEMA", "SECURITYAUDIT",
            "SELECT", "SEMANTICKEYPHRASETABLE", "SEMANTICSIMILARITYDETAILSTABLE",
            "SEMANTICSIMILARITYTABLE", "SESSION_USER", "SET", "SETUSER", "SHUTDOWN", "SOME",
            "STATISTICS", "SYSTEM_USER", "TABLE", "TABLESAMPLE", "TEXTSIZE", "THEN", "THROW",
            "TO", "TOP", "TRAN", "TRANSACTION", "TRIGGER", "TRUNCATE", "TRY_CONVERT", "TSEQUAL",
            "UNION", "UNIQUE", "UNPIVOT", "UPDATE", "UPDATETEXT", "USE", "USER", "VALUES",
            "VARYING", "VIEW", "WAITFOR", "WHEN", "WHERE", "WHILE", "WITH", "WITHIN GROUP",
            "WRITETEXT"
        ];

        var tsqlDataTypes = [
            "BIGINT", "BINARY", "BIT", "CHAR", "DATE", "DATETIME", "DATETIME2",
            "DATETIMEOFFSET", "DECIMAL", "FLOAT", "GEOGRAPHY", "GEOMETRY", "HIERARCHYID",
            "IMAGE", "INT", "MONEY", "NCHAR", "NTEXT", "NUMERIC", "NVARCHAR", "REAL",
            "ROWVERSION", "SMALLDATETIME", "SMALLINT", "SMALLMONEY", "SQL_VARIANT", "SYSNAME",
            "TEXT", "TIME", "TIMESTAMP", "TINYINT", "UNIQUEIDENTIFIER", "VARBINARY", "VARCHAR", "XML"
        ];

        var tsqlBuiltInFunctions = [
            { name: "ABS", args: "${1:number}" },
            { name: "APPROX_COUNT_DISTINCT", args: "${1:expression}" },
            { name: "ASCII", args: "${1:character_expression}" },
            { name: "AVG", args: "${1:expression}" },
            { name: "CAST", args: "${1:expression} AS ${2:data_type}" },
            { name: "CEILING", args: "${1:number}" },
            { name: "CHAR", args: "${1:integer_expression}" },
            { name: "CHARINDEX", args: "${1:expression_to_find}, ${2:expression_to_search}" },
            { name: "CHOOSE", args: "${1:index}, ${2:value1}, ${3:value2}" },
            { name: "COALESCE", args: "${1:expression1}, ${2:expression2}" },
            { name: "COL_NAME", args: "${1:table_id}, ${2:column_id}" },
            { name: "CONCAT", args: "${1:string1}, ${2:string2}" },
            { name: "CONCAT_WS", args: "${1:separator}, ${2:string1}, ${3:string2}" },
            { name: "CONVERT", args: "${1:data_type}, ${2:expression}${3:, style}" },
            { name: "COUNT", args: "${1:*}" },
            { name: "COUNT_BIG", args: "${1:*}" },
            { name: "DATABASEPROPERTYEX", args: "${1:database}, ${2:property}" },
            { name: "DATEADD", args: "${1:datepart}, ${2:number}, ${3:date}" },
            { name: "DATEDIFF", args: "${1:datepart}, ${2:startdate}, ${3:enddate}" },
            { name: "DATEDIFF_BIG", args: "${1:datepart}, ${2:startdate}, ${3:enddate}" },
            { name: "DATEFROMPARTS", args: "${1:year}, ${2:month}, ${3:day}" },
            { name: "DATENAME", args: "${1:datepart}, ${2:date}" },
            { name: "DATEPART", args: "${1:datepart}, ${2:date}" },
            { name: "DAY", args: "${1:date}" },
            { name: "DB_ID", args: "${1:database_name}" },
            { name: "DB_NAME", args: "${1:database_id}" },
            { name: "EOMONTH", args: "${1:start_date}${2:, month_to_add}" },
            { name: "FLOOR", args: "${1:number}" },
            { name: "FORMAT", args: "${1:value}, ${2:format}" },
            { name: "GETDATE", args: "" },
            { name: "GETUTCDATE", args: "" },
            { name: "IIF", args: "${1:condition}, ${2:true_value}, ${3:false_value}" },
            { name: "ISDATE", args: "${1:expression}" },
            { name: "ISJSON", args: "${1:expression}" },
            { name: "ISNULL", args: "${1:check_expression}, ${2:replacement_value}" },
            { name: "JSON_MODIFY", args: "${1:expression}, ${2:path}, ${3:new_value}" },
            { name: "JSON_QUERY", args: "${1:expression}${2:, path}" },
            { name: "JSON_VALUE", args: "${1:expression}, ${2:path}" },
            { name: "LEFT", args: "${1:character_expression}, ${2:integer_expression}" },
            { name: "LEN", args: "${1:string_expression}" },
            { name: "LOWER", args: "${1:character_expression}" },
            { name: "LTRIM", args: "${1:character_expression}" },
            { name: "MAX", args: "${1:expression}" },
            { name: "MIN", args: "${1:expression}" },
            { name: "MONTH", args: "${1:date}" },
            { name: "NEWID", args: "" },
            { name: "NULLIF", args: "${1:expression1}, ${2:expression2}" },
            { name: "OBJECT_ID", args: "${1:object_name}${2:, object_type}" },
            { name: "OBJECT_NAME", args: "${1:object_id}${2:, database_id}" },
            { name: "PARSENAME", args: "${1:object_name}, ${2:object_piece}" },
            { name: "PATINDEX", args: "${1:pattern}, ${2:expression}" },
            { name: "POWER", args: "${1:float_expression}, ${2:power}" },
            { name: "QUOTENAME", args: "${1:character_string}" },
            { name: "RAND", args: "${1:seed}" },
            { name: "RANK", args: "" },
            { name: "REPLACE", args: "${1:string_expression}, ${2:pattern}, ${3:replacement}" },
            { name: "REPLICATE", args: "${1:string_expression}, ${2:integer_expression}" },
            { name: "REVERSE", args: "${1:string_expression}" },
            { name: "RIGHT", args: "${1:character_expression}, ${2:integer_expression}" },
            { name: "ROUND", args: "${1:numeric_expression}, ${2:length}" },
            { name: "ROW_NUMBER", args: "" },
            { name: "RTRIM", args: "${1:character_expression}" },
            { name: "SCHEMA_ID", args: "${1:schema_name}" },
            { name: "SCHEMA_NAME", args: "${1:schema_id}" },
            { name: "SCOPE_IDENTITY", args: "" },
            { name: "SPACE", args: "${1:integer_expression}" },
            { name: "STRING_AGG", args: "${1:expression}, ${2:separator}" },
            { name: "STRING_ESCAPE", args: "${1:text}, 'json'" },
            { name: "STRING_SPLIT", args: "${1:string}, ${2:separator}" },
            { name: "STUFF", args: "${1:character_expression}, ${2:start}, ${3:length}, ${4:replace_with}" },
            { name: "SUBSTRING", args: "${1:expression}, ${2:start}, ${3:length}" },
            { name: "SUM", args: "${1:expression}" },
            { name: "SYSDATETIME", args: "" },
            { name: "SYSDATETIMEOFFSET", args: "" },
            { name: "SYSUTCDATETIME", args: "" },
            { name: "TRANSLATE", args: "${1:input_string}, ${2:characters}, ${3:translations}" },
            { name: "TRIM", args: "${1:character_expression}" },
            { name: "TRY_CAST", args: "${1:expression} AS ${2:data_type}" },
            { name: "TRY_CONVERT", args: "${1:data_type}, ${2:expression}${3:, style}" },
            { name: "TYPE_NAME", args: "${1:type_id}" },
            { name: "UPPER", args: "${1:character_expression}" },
            { name: "YEAR", args: "${1:date}" }
        ];

